### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by ghost** [yashovardhan99/HealersDiary#2]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a icon.

Best Regards.

**Comment by yashovardhan99** [comment]
Hi @Yasujizr Thanks a lot for the offer!
I don't presently have an idea but am willing to look at your ideas and designs.
Go ahead, I will be waiting for it!

**Comment by ghost** [comment]
![healthdiary](https://user-images.githubusercontent.com/36993664/42237067-66e53920-7f05-11e8-9c18-d641e53e22e6.jpg)

@yashovardhan99 

Hi, I made a few designs for you. Please tell me if there are places you like or do not like.

**Comment by yashovardhan99** [comment]
@Yasujizr
I kinda like the second and fourth one. I was also thinking we'll be needing a kind of a text logo with the app name. Maybe we can fit the app icon in one of the letters.
I think the notepad icon in the third one can be tweaked a bit. Are there any designs you've thought? Something not in the white and red spectrum? If you google about healing, you'll see that this isn't exactly for doctors although they could use it as well. 
Healers normally rely heavily on their hands, can you do something along those lines?

**Comment by ghost** [comment]
![healer](https://user-images.githubusercontent.com/36993664/42294090-2a8f778c-7fe7-11e8-8996-3b9e94123f38.jpg)


Hi, I will also make a logotype. But first we have to make a logo. Depending on the logo, I will make a logotype. I made two designs on Healing and Hand touch. If you want, we can work as a hand only, apart from the Heart and Heal Icon. If you have a logo you like, you can show an example.

**Comment by yashovardhan99** [comment]
![image](https://user-images.githubusercontent.com/24536718/42306943-7c0b560a-804e-11e8-9664-ea46cc67ee01.png)
@Yasujizr Hi, Have a look at this, this is from a google search but something along this line (not necessarily this complex, a simple design will do) will be really great!

Also, I am currently adding testers for the internal testing of this app. If you are interested, I will need your email ID (Google Account).

**Comment by ghost** [comment]
![healthdiary](https://user-images.githubusercontent.com/36993664/42470817-5a3a6c36-83c4-11e8-87ad-1cf166283665.jpg)

We can change the object in the middle of the hands. If you like it, it can stand. When it does, the diary is not understood.

**Comment by yashovardhan99** [comment]
@Yasujizr This is perfect! No need to change the object, it looks really nice!

**Comment by ghost** [comment]
Hi, Thank u, I send PR.

**Comment by yashovardhan99** [comment]
Hey, thanks for the PR. I've merged it into master.
Before I close this issue though, Are there any specific license requirements for using your images? I'll be later on releasing the app on the play store and I want to give you proper credit for your hard work.
Once again, thanks a lot!

**Comment by ghost** [comment]
I use the creative common license. so you can use it the way you want. :) Thank u too.

**Comment by yashovardhan99** [comment]
Thanks! @Yasujizr
